---
name: VanillaEnchantments
version: 3.1.0
api:
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
- 4.0.0
- 4.0.0-ALPHA1
author: TheAz928
website: Github.com/TheAz928/VanillaEnchantments
main: vanilla\Core
description: "Vanilla enchantments implemention for pmmp"

...
